<script setup lang="ts">
import type { Category } from '@/types/categoryTypes'

interface CategoriesListProps {
  categories: Category[]
  error: Error | null
  loading: boolean
}

defineProps<CategoriesListProps>()
</script>

<template>
  <h1
    class="text-2xl md:text-3xl font-bold mb-6 text-gray-900 tracking-tight text-center md:text-left"
  >
    Categories
  </h1>

  <div v-if="loading" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 md:gap-6">
    <div v-for="n in 2" :key="n" class="bg-gray-100 rounded-xl p-4 md:p-6 animate-pulse shadow-sm">
      <div class="bg-gray-200 h-6 md:h-7 w-3/4 rounded mb-4"></div>
      <div class="bg-gray-200 h-4 md:h-5 w-full rounded"></div>
    </div>
  </div>

  <div
    v-if="error"
    class="flex items-center justify-center p-6 bg-red-50 text-red-600 rounded-lg shadow-md"
  >
    <span class="font-medium">Error: {{ String(error) }}</span>
  </div>

  <div
    v-else-if="!loading && !error && !categories.length"
    class="flex items-center justify-center p-6 text-gray-500 bg-gray-50 rounded-lg shadow-md"
  >
    <span class="text-lg font-medium">No categories found.</span>
  </div>

  <div
    v-else-if="!loading && !error && categories.length"
    class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 md:gap-6"
  >
    <RouterLink
      v-for="category in categories"
      :key="category.id"
      :to="{
        name: 'Category',
        params: { slug: category.autogeneratedSlug },
        query: { id: category.id },
      }"
      class="group"
    >
      <div
        class="flex flex-col h-full bg-white rounded-xl shadow-md hover:shadow-xl transition-all duration-300 ease-in-out p-4 md:p-6 border border-gray-100 hover:border-gray-200"
      >
        <h2
          class="text-lg md:text-xl font-semibold text-gray-800 line-clamp-1 group-hover:text-blue-600 transition-colors duration-200"
        >
          {{ category.name }}
        </h2>
        <p
          class="text-gray-600 mt-2 text-sm md:text-base line-clamp-2 group-hover:text-gray-700 transition-colors duration-200"
        >
          {{ category.description || 'Description coming soon' }}
        </p>
      </div>
    </RouterLink>
  </div>
</template>
