<script setup lang="ts">
import type { Product } from '@/types/productTypes'

defineProps<{
  products: Product[]
  error: Error | null
  loading: boolean
  hasTitle?: boolean
}>()
</script>

<template>
  <h2
    v-if="hasTitle"
    class="text-2xl md:text-3xl font-bold mb-6 text-gray-900 tracking-tight text-center md:text-left"
  >
    Products
  </h2>

  <div v-if="loading" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 md:gap-6">
    <div v-for="n in 6" :key="n" class="bg-gray-100 rounded-xl p-4 md:p-6 animate-pulse shadow-sm">
      <div class="bg-gray-200 w-full aspect-[2/3] rounded-lg mb-4"></div>
      <div class="bg-gray-200 h-6 md:h-7 w-3/4 rounded mb-2"></div>
      <div class="bg-gray-200 h-4 md:h-5 w-1/2 rounded"></div>
    </div>
  </div>

  <div
    v-if="error"
    class="flex items-center justify-center p-6 bg-red-50 text-red-600 rounded-lg shadow-md"
  >
    <span class="font-medium">Error: {{ String(error) }}</span>
  </div>

  <div
    v-else-if="!loading && !error && !products.length"
    class="flex items-center justify-center p-6 text-gray-500 bg-gray-50 rounded-lg shadow-md"
  >
    <span class="text-lg font-medium">No products found.</span>
  </div>

  <div
    v-else-if="!loading && !error && products.length"
    class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 md:gap-6"
  >
    <RouterLink
      v-for="product in products"
      :key="product.id"
      :to="{
        name: 'Product',
        params: { slug: product.autogeneratedSlug },
        query: { id: product.id },
      }"
      class="group"
    >
      <div
        class="flex flex-col h-full bg-white rounded-xl shadow-md hover:shadow-xl transition-all duration-300 ease-in-out p-4 md:p-6 border border-gray-100 hover:border-gray-200"
      >
        <img
          :src="product.hdThumbnailUrl"
          :alt="product.name"
          class="w-full aspect-[2/3] object-cover rounded-lg mb-4 transition-transform duration-300 group-hover:scale-105"
        />
        <h3
          class="text-lg md:text-xl font-semibold text-gray-800 text-center line-clamp-2 group-hover:text-blue-600 transition-colors duration-200"
        >
          {{ product.name }}
        </h3>
        <p
          class="text-xl md:text-2xl font-bold text-gray-900 mt-2 text-center group-hover:text-blue-600 transition-colors duration-200"
        >
          {{ product.defaultDisplayedPriceFormatted }}
        </p>
      </div>
    </RouterLink>
  </div>
</template>
