export interface CategoryResponse {
  total: number
  count: number
  offset: number
  limit: number
  items: Category[]
}

export interface Category {
  id: number
  name: string
  description: string
  autogeneratedSlug: string
  productCount: number
}
