export interface ProductResponse {
  total: number
  count: number
  offset: number
  limit: number
  items: Product[]
}

export interface Product {
  id: number
  name: string
  description: string
  autogeneratedSlug: string
  price: number
  defaultDisplayedPriceFormatted: string
  smallThumbnailUrl: string
  hdThumbnailUrl: string
  originalImageUrl: string
  defaultCategoryId: number
  inStock: boolean
  isGiftCard: boolean
  isSampleProduct: boolean
  isShippingRequired: boolean
  categoryIds: number[]
  options: ProductOption[]
  relatedProducts: RelatedProducts
}

interface ProductOption {
  defaultChoice: string
  name: string
  type: string
  choices: ProductOptionChoice[]
}

interface ProductOptionChoice {
  priceModifier: number
  priceModifierType: string
  text: string
}

interface RelatedProducts {
  productIds: number[]
  relatedCategory: RelatedCategory
}

interface RelatedCategory {
  enabled: boolean
  categoryId: number
  productCount: number
}
